defmodule LiveDebuggerTourWeb.Live.ComponentsTreeLive do
  use LiveDebuggerTourWeb, :live_view

  use LiveDebuggerTour.Page,
    number: 5,
    title: "Components Tree",
    description:
      "Visualize complex UI hierarchies with multiple LiveComponents, using the highlight feature to map the tree structure to the browser view."

  alias LiveDebugger.Tour
  alias LiveDebugger.App.Web.Helpers.Routes, as: RoutesHelper
  alias LiveDebuggerTourWeb.Components.TourComponents
  alias LiveDebuggerTourWeb.Live.ComponentsTree.WidgetCard

  @initial_widgets [
    %{
      id: "weather",
      label: "Weather",
      icon: "hero-sun",
      icon_color: "text-warning",
      value: "24°C",
      description: "Current temperature"
    },
    %{
      id: "visitors",
      label: "Visitors",
      icon: "hero-users",
      icon_color: "text-info",
      value: "1,429",
      description: "Active users"
    },
    %{
      id: "uptime",
      label: "Uptime",
      icon: "hero-arrow-trending-up",
      icon_color: "text-success",
      value: "99.9%",
      description: "System uptime"
    },
    %{
      id: "alerts",
      label: "Alerts",
      icon: "hero-bell-alert",
      icon_color: "text-error",
      value: "3 new",
      description: "Pending alerts"
    }
  ]

  @tour_steps [
    %{
      id: 1,
      title: "Explore the dashboard",
      description:
        "The widget dashboard above contains multiple LiveComponents. " <>
          "Each card is a separate <code>WidgetCard</code> component with its own CID (Component ID) in the debugger tree.",
      target: "widget-dashboard",
      action: {:client_spotlight, []},
      icon: "hero-squares-2x2"
    },
    %{
      id: 2,
      title: "Open the tree & hover to highlight",
      description:
        "Open the Components Tree in the LiveDebugger panel. " <>
          "<span class=\"text-success font-bold\">Hovering</span> over a node <span class=\"text-success font-bold\">highlights</span> the corresponding DOM element in the browser — " <>
          "try hovering over different widget entries to see which card lights up.",
      target: "#components-tree",
      action: {:highlight, [dismiss: "click-anywhere"]},
      icon: "hero-cursor-arrow-rays"
    },
    %{
      id: 3,
      title: "Toggle widgets",
      description:
        "Use the toggle buttons below the dashboard to show or hide widgets. " <>
          "Watch the Components Tree update in real-time as LiveComponents are added and removed from the page.",
      target: "widget-controls",
      action: {:client_spotlight, []},
      icon: "hero-eye-slash"
    },
    %{
      id: 4,
      title: "Navigate to a component",
      description:
        "Click a widget entry in the Components Tree to select it. " <>
          "The debugger now shows that component's assigns and state instead of the parent LiveView.",
      target: "#components-tree details > :last-child > :first-child",
      action: {:highlight, [dismiss: "click-target"]},
      icon: "hero-arrow-right-circle"
    },
    %{
      id: 5,
      title: "Check its traces",
      description:
        "Click a widget's <span class=\"text-success font-bold\">Interact</span> button a few times, then look at the Callback traces section. " <>
          "You'll see the <code>handle_event</code> calls generated by your clicks on that component.",
      target: :callback_traces_section,
      action: {:spotlight, [dismiss: "click-anywhere"]},
      icon: "hero-magnifying-glass"
    }
  ]

  @impl true
  def mount(_params, _session, socket) do
    initial_ids = MapSet.new(@initial_widgets, & &1.id)

    socket =
      socket
      |> tour_page_assigns(@tour_steps)
      |> assign(
        widgets: @initial_widgets,
        visible: initial_ids
      )

    {:ok, socket}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <Layouts.app flash={@flash}>
      <TourComponents.header
        number={@page_number}
        name={@page_title}
        description="Visualize complex UI hierarchies with multiple LiveComponents, using the highlight feature to map the tree structure to the browser view."
      />
      <TourComponents.progress_bar tour_steps={@tour_steps} completed_steps={@completed_steps} />

      <div class="alert alert-info mb-6">
        <.icon name="hero-information-circle" class="size-5" />
        <div>
          <p class="font-semibold">What is the Components Tree?</p>
          <p class="text-sm">
            The Components Tree shows the hierarchy of all LiveComponents rendered inside
            a LiveView. Each component gets a unique CID (Component ID) that you can click
            to inspect its assigns and callback traces. Hovering a node highlights
            the corresponding element in the browser.
          </p>
        </div>
      </div>

      <div id="widget-dashboard" class="card bg-base-100 shadow-sm mb-6">
        <div class="card-body">
          <h3 class="card-title text-base">
            <.icon name="hero-squares-2x2" class="size-5 text-primary" /> Widget Dashboard
          </h3>
          <p class="text-sm text-base-content/70">
            Each widget below is a LiveComponent with its own CID in the debugger tree.
            Click "Interact" to create local state changes visible in the assigns inspector.
          </p>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
            <.live_component
              :for={widget <- Enum.filter(@widgets, &MapSet.member?(@visible, &1.id))}
              module={WidgetCard}
              id={"widget-#{widget.id}"}
              label={widget.label}
              icon={widget.icon}
              icon_color={widget.icon_color}
              value={widget.value}
              description={widget.description}
            />
          </div>
          <div
            id="widget-controls"
            class="flex justify-center bg-base-100 flex-wrap gap-2 mt-4 py-4 border-t border-base-300"
          >
            <button
              :for={widget <- @widgets}
              phx-click="toggle_widget"
              phx-value-id={widget.id}
              class={[
                "btn btn-sm",
                if(MapSet.member?(@visible, widget.id), do: "btn-soft", else: "btn-ghost opacity-50")
              ]}
            >
              <.icon name={widget.icon} class="size-4" />
              {widget.label}
            </button>
          </div>
        </div>
      </div>

      <div id="tour-cards" class="space-y-4">
        <TourComponents.tour_step
          :for={step <- @tour_steps}
          step={step}
          completed={MapSet.member?(@completed_steps, step.id)}
        >
          <:button :if={step.id == 2}>
            <button
              id={"tour-btn-#{step.id}"}
              phx-click={
                Tour.highlight_JS("#components-tree")
                |> JS.concat(Tour.highlight_JS(:show_components_tree, clear: false))
                |> JS.push("activate_step", value: %{step: step.id})
              }
              class="btn btn-sm btn-soft"
            >
              <.icon name="hero-viewfinder-circle" class="size-4" /> Highlight
            </button>
          </:button>
        </TourComponents.tour_step>
      </div>

      <TourComponents.client_spotlight_hook />
      <TourComponents.clear_spotlight_button :if={@current_step != nil} />

      <div class="flex justify-center gap-3">
        <TourComponents.restart_page url={@page_path} />
        <TourComponents.reload_debugger url={RoutesHelper.debugger_node_inspector(self())} />
      </div>

      <TourComponents.navigation prev_page={@prev_page} next_page={@next_page} />
    </Layouts.app>
    """
  end

  @impl true
  def handle_event("toggle_widget", %{"id" => id}, socket) do
    visible =
      if MapSet.member?(socket.assigns.visible, id) do
        MapSet.delete(socket.assigns.visible, id)
      else
        MapSet.put(socket.assigns.visible, id)
      end

    {:noreply, assign(socket, :visible, visible)}
  end
end
